In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
import numpy as np

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
np.empty((2,3,3))

array([[[  4.67296746e-307,   1.69121096e-306,   1.29061074e-306],
        [  1.69119873e-306,   1.78019082e-306,   8.34441742e-308],
        [  1.78022342e-306,   6.23058028e-307,   9.79107872e-307]],

       [[  6.89807188e-307,   7.56594375e-307,   6.23060065e-307],
        [  1.78021527e-306,   8.34454050e-308,   1.11261027e-306],
        [  1.15706896e-306,   1.33512173e-306,   4.07714063e+161]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [18]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
arr = np.array([1,2,3,4,5])

In [22]:
arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float64)

In [24]:
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [26]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [28]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)

In [29]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [30]:
numeric_strings.dtype

dtype('S4')

In [31]:
int_array = np.arange(10)

In [32]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [33]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [34]:
empty_uint32 = np.empty(8,dtype='u4')

In [35]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [36]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [37]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [38]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [39]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [40]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [41]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [42]:
arr = np.arange(10)

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[5]

5

In [45]:
arr[5:8]

array([5, 6, 7])

In [46]:
arr[5:8] = 12

In [47]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
arr_slice = arr[5:8]

In [49]:
arr_slice[1] = 12345

In [50]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [51]:
arr_slice[:] = 64

In [52]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
arr2d[2]

array([7, 8, 9])

In [55]:
arr2d[0][2]

3

In [56]:
arr2d[0,2]

3

In [57]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [58]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
old_values = arr3d[0].copy()

In [61]:
arr3d[0] = 42

In [62]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d[0] = old_values

In [64]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[1,0]

array([7, 8, 9])

In [66]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [70]:
arr2d[1,:2]

array([4, 5])

In [71]:
arr2d[2,:1]

array([7])

In [72]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [73]:
arr2d[:2,1:] = 0

In [74]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [75]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [76]:
data = np.random.randn(7,4)

In [77]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [78]:
data

array([[ 0.33468731,  0.48516099,  0.9127049 , -1.146809  ],
       [-1.69386818,  0.80919932, -0.42284722,  1.60483622],
       [-0.16438586,  0.86490453, -1.90338044,  1.01645895],
       [-0.38602897, -0.09644004,  0.54684861,  2.05420252],
       [-1.23077021,  0.40250673,  1.37036191,  2.52075072],
       [ 0.37918108,  1.25145338,  1.23473298, -0.95783014],
       [ 0.23484898, -1.59915055,  2.05856305, -0.61557546]])

In [79]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [80]:
data[names == 'Bob']

array([[ 0.33468731,  0.48516099,  0.9127049 , -1.146809  ],
       [-0.38602897, -0.09644004,  0.54684861,  2.05420252]])

In [81]:
data[names == 'Bob',2:]

array([[ 0.9127049 , -1.146809  ],
       [ 0.54684861,  2.05420252]])

In [82]:
data[names == 'Bob',3]

array([-1.146809  ,  2.05420252])

In [83]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [84]:
data[~(names == 'Bob')]

array([[-1.69386818,  0.80919932, -0.42284722,  1.60483622],
       [-0.16438586,  0.86490453, -1.90338044,  1.01645895],
       [-1.23077021,  0.40250673,  1.37036191,  2.52075072],
       [ 0.37918108,  1.25145338,  1.23473298, -0.95783014],
       [ 0.23484898, -1.59915055,  2.05856305, -0.61557546]])

In [85]:
mask = (names == 'Bob')| (names == 'Will')

In [86]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [87]:
data[mask]

array([[ 0.33468731,  0.48516099,  0.9127049 , -1.146809  ],
       [-0.16438586,  0.86490453, -1.90338044,  1.01645895],
       [-0.38602897, -0.09644004,  0.54684861,  2.05420252],
       [-1.23077021,  0.40250673,  1.37036191,  2.52075072]])

In [88]:
data[data < 0] = 0

In [89]:
data

array([[ 0.33468731,  0.48516099,  0.9127049 ,  0.        ],
       [ 0.        ,  0.80919932,  0.        ,  1.60483622],
       [ 0.        ,  0.86490453,  0.        ,  1.01645895],
       [ 0.        ,  0.        ,  0.54684861,  2.05420252],
       [ 0.        ,  0.40250673,  1.37036191,  2.52075072],
       [ 0.37918108,  1.25145338,  1.23473298,  0.        ],
       [ 0.23484898,  0.        ,  2.05856305,  0.        ]])

In [90]:
data[names != 'Joe'] = 7

In [91]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.80919932,  0.        ,  1.60483622],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.37918108,  1.25145338,  1.23473298,  0.        ],
       [ 0.23484898,  0.        ,  2.05856305,  0.        ]])

In [92]:
arr = np.empty((8,4))

In [93]:
for i in range(8):
    arr[i] = i

In [94]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [95]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [96]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [97]:
arr = np.arange(32).reshape((8,4))

In [98]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [99]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [100]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [101]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [102]:
arr = np.arange(15).reshape((3,5))

In [103]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [104]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [105]:
arr = np.random.randn(6,3)

In [106]:
np.dot(arr.T,arr)

array([[  5.47975347,  -3.10531015,  -0.56209256],
       [ -3.10531015,  11.46333341,  -1.59556586],
       [ -0.56209256,  -1.59556586,   4.22828376]])

In [107]:
arr = np.arange(16).reshape((2,2,4))

In [108]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [109]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [110]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [111]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [112]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [113]:
arr = np.arange(10)

In [114]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [115]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [116]:
x = np.random.randn(8)

In [117]:
y = np.random.randn(8)

In [118]:
x

array([ 0.4093896 ,  0.20743462,  0.36426916,  0.52710332, -0.37830044,
       -0.6329054 , -0.74598377, -0.66765286])

In [119]:
y

array([ 0.84971758, -0.13552592,  1.38089476,  1.21494114,  0.41154949,
        0.56912886,  2.63170854,  0.47897849])

In [120]:
np.maximum(x,y)

array([ 0.84971758,  0.20743462,  1.38089476,  1.21494114,  0.41154949,
        0.56912886,  2.63170854,  0.47897849])

In [121]:
arr = np.random.randn(7) * 5

In [122]:
np.modf(arr)

(array([ 0.25121454, -0.22301736, -0.7066143 ,  0.46683372, -0.85176859,
        -0.11185622,  0.17096808]), array([ 6., -6., -5.,  2., -4., -2.,  2.]))

In [123]:
points = np.arange(-5,5,0.01)

In [124]:
xs,ys = np.meshgrid(points,points)

In [125]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [126]:
import matplotlib.pyplot as plt

In [127]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [128]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [129]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

In [130]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [131]:
xaar = np.array([1.1,1.2,1.3,1.4,1.5])

In [132]:
yaar = np.array([2.1,2.2,2.3,2.4,2.5])

In [133]:
cond = np.array([True,False,True,True,False])

In [134]:
result = [(x if c else y) for x,y,c in zip(xaar,yaar,cond)]

In [135]:
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [136]:
result = np.where(cond,xaar,yaar)

In [137]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [138]:
arr = np.random.randn(4,4)

In [139]:
arr

array([[ 0.24168458, -0.9149037 , -1.54971393, -0.1193908 ],
       [-0.53055756, -0.0384746 , -0.83679405,  0.68004335],
       [-0.41332181,  0.0446863 ,  0.6661797 , -0.54427376],
       [ 1.69546657, -2.15008101,  0.09297067, -0.33088536]])

In [140]:
np.where(arr>0,2,-2)

array([[ 2, -2, -2, -2],
       [-2, -2, -2,  2],
       [-2,  2,  2, -2],
       [ 2, -2,  2, -2]])

In [141]:
np.where(arr>0,2,arr)

array([[ 2.        , -0.9149037 , -1.54971393, -0.1193908 ],
       [-0.53055756, -0.0384746 , -0.83679405,  2.        ],
       [-0.41332181,  2.        ,  2.        , -0.54427376],
       [ 2.        , -2.15008101,  2.        , -0.33088536]])

In [142]:
arr = np.random.randn(5,4)

In [143]:
arr.mean()

0.16284100939468946

In [144]:
arr

array([[ 0.53568757, -0.24052534, -0.26608894,  0.4994062 ],
       [ 0.49187939,  1.61181091, -0.74931289, -0.42205713],
       [-0.54852374, -0.66275715,  0.64355162, -0.24553548],
       [ 0.97651064,  1.8739286 ,  0.38003217,  0.13388441],
       [ 2.08783701, -1.36834313, -0.39118121, -1.08338332]])

In [145]:
np.mean(arr)

0.16284100939468946

In [146]:
arr.sum()

3.2568201878937892

In [147]:
arr.mean(axis=1)

array([ 0.13211987,  0.23308007, -0.20331619,  0.84108895, -0.18876766])

In [148]:
arr.sum(0)

array([ 3.54339087,  1.21411389, -0.38299925, -1.11768532])

In [149]:
arr = np.array([[1,1,2],[3,4,5],[6,7,8]])

In [150]:
arr

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
arr.cumsum(0)

array([[ 1,  1,  2],
       [ 4,  5,  7],
       [10, 12, 15]], dtype=int32)

In [152]:
arr.cumprod(1)

array([[  1,   1,   2],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [153]:
arr = np.random.randn(100)

In [154]:
(arr > 0).sum()

56

In [155]:
bools = np.array([False,False,True,False])

In [156]:
bools.any()

True

In [157]:
bools.all()

False

In [159]:
arr = np.random.randn(8)

In [160]:
arr

array([ 0.70019238,  0.68931359, -0.08364232,  0.53359575, -1.56298186,
        1.03617266,  1.52131584, -0.19875379])

In [161]:
arr.sort()

In [162]:
arr

array([-1.56298186, -0.19875379, -0.08364232,  0.53359575,  0.68931359,
        0.70019238,  1.03617266,  1.52131584])

In [163]:
arr = np.random.randn(5,3)

In [164]:
arr

array([[ 0.53974344, -0.26529324,  0.19285553],
       [ 0.5953855 , -0.8553606 , -0.3688837 ],
       [ 0.05791197, -0.17245037,  0.40502596],
       [ 2.51863309,  0.99675413,  0.97774685],
       [-1.14205544,  0.87665708, -0.49309848]])

In [165]:
arr.sort(1)

In [166]:
arr

array([[-0.26529324,  0.19285553,  0.53974344],
       [-0.8553606 , -0.3688837 ,  0.5953855 ],
       [-0.17245037,  0.05791197,  0.40502596],
       [ 0.97774685,  0.99675413,  2.51863309],
       [-1.14205544, -0.49309848,  0.87665708]])

In [167]:
large_arr = np.random.randn(1000)

In [168]:
large_arr.sort()

In [170]:
large_arr[int(0.05 * len(large_arr))]

-1.6253299214823027

In [171]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [172]:
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [173]:
ints = np.array([3,3,3,2,2,1,1,4,4])

In [174]:
np.unique(ints)

array([1, 2, 3, 4])

In [175]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [176]:
values = np.array([6,0,0,3,2,5,6])

In [177]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [178]:
arr = np.arange(10)

In [179]:
np.save('some_array',arr)

In [180]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
np.savez('array_archive.npz',a=arr,b=arr)

In [182]:
arch = np.load('array_archive.npz')

In [183]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
!type array_ex.txt

0.580052,0.186730,1.040717,1.134411
0.194163,-0.636917,-0.938659,0.124094
-0.126410,0.268607,-0.695724,0.047428


In [198]:
arr = np.loadtxt('array_ex.txt',delimiter=',')

In [199]:
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428]])

In [200]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])

In [201]:
y = np.array([[6.,23.],[-1,7],[8,9]])

In [202]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [203]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [204]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [205]:
np.ones(3)

array([ 1.,  1.,  1.])

In [206]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [207]:
from numpy.linalg import inv,qr

In [210]:
X = np.random.randn(5,5)

In [211]:
mat = X.T.dot(X)

In [212]:
inv(mat)

array([[ 0.57528877,  0.17200151,  0.27869666, -0.29017133,  0.37456633],
       [ 0.17200151,  0.20469531,  0.06073254, -0.1716202 ,  0.25794981],
       [ 0.27869666,  0.06073254,  0.75084769,  0.26309574,  0.65682631],
       [-0.29017133, -0.1716202 ,  0.26309574,  0.93564885, -0.44980952],
       [ 0.37456633,  0.25794981,  0.65682631, -0.44980952,  1.83457001]])

In [213]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   5.01127033e-17,  -8.46322447e-17,
          3.44425678e-18,   3.73162582e-16],
       [  2.05207825e-16,   1.00000000e+00,   1.12968822e-16,
         -4.11085541e-17,   1.08817654e-16],
       [  1.00539107e-16,   1.32824400e-16,   1.00000000e+00,
          2.30716104e-17,  -4.36688005e-16],
       [  8.13303171e-17,  -3.88023641e-17,  -2.86303125e-16,
          1.00000000e+00,   1.67296111e-16],
       [  1.09043975e-16,   5.58644751e-17,   6.12144307e-17,
         -1.05152706e-16,   1.00000000e+00]])

In [214]:
q,r = qr(mat)

In [215]:
r

array([[-7.12874599,  4.90346001,  8.23947323, -5.82781349, -3.7171621 ],
       [ 0.        , -6.53929314,  1.60181479, -1.98925369, -0.1272737 ],
       [ 0.        ,  0.        , -2.87750896,  1.76036821,  1.67609058],
       [ 0.        ,  0.        ,  0.        , -1.0522432 , -0.30675467],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.48758828]])

In [216]:
samples = np.random.normal(size=(4,4))

In [217]:
samples

array([[ 0.97890436,  0.09029441,  1.6932852 , -1.38329323],
       [ 1.25629133,  0.78060757,  0.88254853,  0.81954319],
       [ 0.26578742,  0.74218829,  0.74722556, -0.75135496],
       [ 1.79428006,  0.03140466,  0.03470737, -0.63952052]])

In [218]:
from random import normalvariate

In [219]:
N = 1000000

In [221]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

708 ms ± 3.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [222]:
%timeit np.random.normal(size=N)

28.1 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [223]:
nsteps = 1000

In [224]:
draws = np.random.randint(0,2,size=nsteps)

In [246]:
steps = np.where(draws > 0,1,-1)

In [259]:
steps

array([[ 1, -1,  1, ...,  1, -1,  1],
       [-1,  1,  1, ...,  1, -1, -1],
       [-1,  1, -1, ...,  1, -1,  1],
       ..., 
       [ 1, -1,  1, ..., -1,  1, -1],
       [-1,  1,  1, ...,  1, -1,  1],
       [-1, -1, -1, ...,  1, -1,  1]])

In [247]:
walk = steps.cumsum()

In [258]:
walk

array([  1,   0,   1,   2,   1,   0,  -1,   0,  -1,  -2,  -3,  -4,  -3,
        -4,  -3,  -2,  -3,  -2,  -3,  -4,  -5,  -4,  -5,  -6,  -7,  -8,
        -9, -10,  -9,  -8,  -9, -10,  -9,  -8,  -9, -10, -11, -12, -11,
       -10, -11, -10,  -9, -10,  -9, -10, -11, -10, -11, -10,  -9, -10,
        -9, -10,  -9,  -8,  -7,  -6,  -7,  -6,  -7,  -6,  -5,  -4,  -5,
        -6,  -5,  -4,  -5,  -4,  -5,  -4,  -5,  -6,  -5,  -4,  -3,  -2,
        -1,  -2,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11,
       -12, -11, -12, -11, -12, -11, -12, -11, -12, -11, -12, -11, -10,
       -11, -10, -11, -10, -11, -12, -13, -12, -11, -12, -13, -14, -15,
       -16, -15, -14, -13, -12, -11, -12, -13, -14, -13, -14, -13, -14,
       -13, -14, -15, -16, -17, -18, -17, -18, -19, -20, -21, -22, -21,
       -20, -21, -22, -21, -22, -21, -20, -19, -18, -17, -18, -19, -20,
       -21, -22, -21, -20, -21, -20, -21, -22, -23, -24, -23, -22, -23,
       -22, -21, -22, -21, -22, -21, -22, -21, -20, -19, -18, -1

In [248]:
walk.min()

-29

In [249]:
walk.max()

12

In [250]:
(np.abs(walk) >= 10).argmax()

27

In [251]:
nwalks = 5000

In [252]:
nsteps = 1000

In [253]:
draws = np.random.randint(0,2,size=(nwalks,nsteps))

In [254]:
steps = np.where(draws > 0,1,-1)

In [260]:
steps

array([[ 1, -1,  1, ...,  1, -1,  1],
       [-1,  1,  1, ...,  1, -1, -1],
       [-1,  1, -1, ...,  1, -1,  1],
       ..., 
       [ 1, -1,  1, ..., -1,  1, -1],
       [-1,  1,  1, ...,  1, -1,  1],
       [-1, -1, -1, ...,  1, -1,  1]])

In [263]:
walks = steps.cumsum(1)

In [264]:
walks

array([[  1,   0,   1, ...,  32,  31,  32],
       [ -1,   0,   1, ..., -10, -11, -12],
       [ -1,   0,  -1, ..., -14, -15, -14],
       ..., 
       [  1,   0,   1, ...,  12,  13,  12],
       [ -1,   0,   1, ...,  -6,  -7,  -6],
       [ -1,  -2,  -3, ...,  24,  23,  24]], dtype=int32)

In [265]:
walks.max()

145

In [266]:
walks.min()

-112

In [267]:
hits30 = (np.abs(walks) >= 30).any(1)

In [268]:
hits30

array([ True, False,  True, ...,  True,  True,  True], dtype=bool)

In [269]:
hits30.sum()

3396

In [271]:
crossing_times = (np.abs(walks) >= 30).argmax(1)

In [272]:
crossing_times.mean()

344.36520000000002