In [1]:
from pandas import Series,DataFrame

In [2]:
import pandas as pd

In [3]:
obj = Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [3]:
import numpy as np

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [21]:
obj3 = Series(sdata)

In [22]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [23]:
states = ['California','Ohio','Oregon','Texas']

In [24]:
obj4 = Series(sdata,index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name = 'population'

In [33]:
obj4.index.name = 'state'

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)

In [38]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [39]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [40]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])

In [41]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [45]:
frame2.ix['three']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [48]:
frame2['debt'] = np.arange(5.)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [50]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [51]:
frame2['debt'] = val

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [53]:
frame2['eastern'] = frame2.state == 'Ohio'

In [54]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [55]:
del frame2['eastern']

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [58]:
frame3 = DataFrame(pop)

In [59]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [60]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [61]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:3]}

In [63]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   NaN

In [64]:
frame3.index.name = 'year';frame3.columns.name='state'

In [65]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [66]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [68]:
obj = Series(range(3),index=['a','b','c'])

In [69]:
index = obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index[1:]

Index(['b', 'c'], dtype='object')

In [72]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [73]:
index = pd.Index(np.arange(3))

In [74]:
obj2 = Series([1.5,-2.5,0],index=index)

In [75]:
obj2.index is index

True

In [76]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [77]:
'Ohio' in frame3.columns

True

In [78]:
2003 in frame3.index

False

In [79]:
obj = Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [80]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [81]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [82]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [83]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [84]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [85]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [86]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [87]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [146]:
frame2 = frame.reindex(['a','b','c','d'],method='ffill')

In [147]:
frame2

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [125]:
states = ['Texas','Utah','California']

In [141]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [160]:
frame.reindex(index=['a','b','c','d'],columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [145]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [151]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [152]:
new_obj = obj.drop('c')

In [153]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [154]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [155]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [156]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [171]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [172]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [5]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [6]:
obj['b']

1.0

In [7]:
obj[1]

1.0

In [8]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [9]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [10]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [11]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [12]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [13]:
obj['b':'c'] = 5

In [14]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [16]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [17]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [19]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [20]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [21]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [22]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [23]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [24]:
data[data < 5] = 0

In [25]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [27]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [28]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [29]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [30]:
data.ix[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [31]:
data.ix[data.three > 5,:3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [4]:
s1 = Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [5]:
s2 = Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [6]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [7]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [8]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [9]:
df1 = DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [10]:
df2 = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [11]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [12]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [13]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [14]:
df1.add(df2,fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [16]:
df1.reindex(columns=df2.columns,fill_value=0)

b    d  e
Ohio      0.0  2.0  0
Texas     3.0  5.0  0
Colorado  6.0  8.0  0

In [17]:
arr = np.arange(12.).reshape((3,4))

In [18]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [19]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [20]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [21]:
frame = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [23]:
series = frame.ix[0]

In [24]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [25]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [26]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [27]:
series2 = Series(range(3),index=['b','e','f'])

In [28]:
series2

b    0
e    1
f    2
dtype: int32

In [29]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [30]:
series3 = frame['d']

In [31]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [32]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [33]:
frame = DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [34]:
frame

b         d         e
Utah    0.749066 -1.381553 -0.967471
Ohio   -0.151263  0.055201 -0.259749
Texas  -0.105844  0.966603  0.162240
Oregon -1.123679 -0.367877  0.902263

In [35]:
np.abs(frame)

b         d         e
Utah    0.749066  1.381553  0.967471
Ohio    0.151263  0.055201  0.259749
Texas   0.105844  0.966603  0.162240
Oregon  1.123679  0.367877  0.902263

In [36]:
f = lambda x:x.max() - x.min()

In [37]:
frame.apply(f)

b    1.872745
d    2.348156
e    1.869735
dtype: float64

In [38]:
frame.apply(f,axis=1)

Utah      2.130620
Ohio      0.314950
Texas     1.072446
Oregon    2.025942
dtype: float64

In [39]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [40]:
frame.apply(f)

b         d         e
min -1.123679 -1.381553 -0.967471
max  0.749066  0.966603  0.902263

In [41]:
format = lambda x: '%.2f' % x

In [42]:
frame.applymap(format)

b      d      e
Utah     0.75  -1.38  -0.97
Ohio    -0.15   0.06  -0.26
Texas   -0.11   0.97   0.16
Oregon  -1.12  -0.37   0.90

In [43]:
frame['e'].map(format)

Utah      -0.97
Ohio      -0.26
Texas      0.16
Oregon     0.90
Name: e, dtype: object

In [44]:
obj = Series(range(4),index=['d','a','b','c'])

In [45]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [46]:
frame = DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [47]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [48]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [49]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [50]:
obj = Series([4,7,-3,2])

In [55]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [57]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [58]:
obj = Series([4,np.nan,7,np.nan,-3,2])

In [59]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [60]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [61]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [64]:
frame.sort_index(by='b')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [65]:
frame.sort_index(by=['a','b'])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [70]:
obj = Series([7,-5,7,4,2,0,4])

In [71]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [72]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [73]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [74]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [75]:
frame = DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [76]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [77]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [78]:
obj = Series(range(5),index=['a','a','b','b','c'])

In [79]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [80]:
obj.index.is_unique

False

In [81]:
obj['a']

a    0
a    1
dtype: int32

In [82]:
obj['c']

4

In [91]:
df = DataFrame(np.random.randn(4,3),index=['a','a','b','b'],columns=['x','y','z'])

In [92]:
df

x         y         z
a -0.394410 -0.559147  0.504090
a  1.530127 -0.420259 -0.968753
b -0.252889 -0.246377  1.036906
b -0.285836 -1.801588 -0.452491

In [93]:
df['x']

a   -0.394410
a    1.530127
b   -0.252889
b   -0.285836
Name: x, dtype: float64

In [97]:
df.ix['b']

x         y         z
b -0.252889 -0.246377  1.036906
b -0.285836 -1.801588 -0.452491

In [98]:
df = DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [99]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [100]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [101]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [102]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [103]:
df.idxmax()

one    b
two    d
dtype: object

In [104]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [105]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [106]:
obj = Series(['a','a','b','c']*4)

In [107]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [125]:
obj = Series(['c','a','d','a','a','b','b','c','c'])

In [126]:
uniques = obj.unique()

In [128]:
uniques.sort()

In [129]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [130]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [134]:
pd.value_counts(obj.values,sort=False)

c    3
b    2
a    3
d    1
dtype: int64

In [135]:
mask = obj.isin(['b','c'])

In [136]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [138]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [139]:
data = DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})

In [140]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [145]:
result = data.apply(pd.value_counts).fillna(0)

In [146]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [4]:
string_data = Series(['aardvark','artichoke',np.nan,'avocado'])

In [5]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [6]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data[0] = None

In [8]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA

In [11]:
data = Series([1,NA,3.5,NA,7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [15]:
cleaned = data.dropna()

In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = NA

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = DataFrame(np.random.randn(7,3))

In [24]:
df.ix[:4,1] = NA;df.ix[:2,2] = NA

In [25]:
df

0        1         2
0  1.163784      NaN       NaN
1  1.292495      NaN       NaN
2 -0.035068      NaN       NaN
3  1.653173      NaN  0.308578
4  1.383296      NaN  1.338002
5  1.374205 -0.04212 -0.565854
6 -0.195817  1.34551  0.049260

In [30]:
df.dropna(thresh=2)

0        1         2
3  1.653173      NaN  0.308578
4  1.383296      NaN  1.338002
5  1.374205 -0.04212 -0.565854
6 -0.195817  1.34551  0.049260

In [31]:
df.fillna(0)

0        1         2
0  1.163784  0.00000  0.000000
1  1.292495  0.00000  0.000000
2 -0.035068  0.00000  0.000000
3  1.653173  0.00000  0.308578
4  1.383296  0.00000  1.338002
5  1.374205 -0.04212 -0.565854
6 -0.195817  1.34551  0.049260

In [32]:
df.fillna({1:0.5,2:-1})

0        1         2
0  1.163784  0.50000 -1.000000
1  1.292495  0.50000 -1.000000
2 -0.035068  0.50000 -1.000000
3  1.653173  0.50000  0.308578
4  1.383296  0.50000  1.338002
5  1.374205 -0.04212 -0.565854
6 -0.195817  1.34551  0.049260

In [33]:
_ = df.fillna(0,inplace=True)

In [34]:
df

0        1         2
0  1.163784  0.00000  0.000000
1  1.292495  0.00000  0.000000
2 -0.035068  0.00000  0.000000
3  1.653173  0.00000  0.308578
4  1.383296  0.00000  1.338002
5  1.374205 -0.04212 -0.565854
6 -0.195817  1.34551  0.049260

In [35]:
df = DataFrame(np.random.randn(6,3))

In [37]:
df.ix[2:,1] = NA;df.ix[4:,2] = NA

In [38]:
df

0         1         2
0 -0.827188 -0.283083 -0.240857
1 -0.340518 -1.270059 -0.058859
2 -0.723805       NaN  0.956293
3  0.742571       NaN -0.534378
4  0.271638       NaN       NaN
5 -0.480318       NaN       NaN

In [39]:
df.fillna(method='ffill')

0         1         2
0 -0.827188 -0.283083 -0.240857
1 -0.340518 -1.270059 -0.058859
2 -0.723805 -1.270059  0.956293
3  0.742571 -1.270059 -0.534378
4  0.271638 -1.270059 -0.534378
5 -0.480318 -1.270059 -0.534378

In [40]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.827188 -0.283083 -0.240857
1 -0.340518 -1.270059 -0.058859
2 -0.723805 -1.270059  0.956293
3  0.742571 -1.270059 -0.534378
4  0.271638       NaN -0.534378
5 -0.480318       NaN -0.534378

In [41]:
data = Series([1.,NA,3.5,NA,7])

In [42]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [5]:
data = Series(np.random.randn(10),index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])

In [6]:
data

a  1   -0.749082
   2    0.852343
   3   -0.577507
b  1   -0.432139
   2    0.043440
   3    0.931063
c  1    0.435406
   2    2.030317
d  2    2.258260
   3   -1.096666
dtype: float64

In [7]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [8]:
data['b']

1   -0.432139
2    0.043440
3    0.931063
dtype: float64

In [9]:
data['b':'c']

b  1   -0.432139
   2    0.043440
   3    0.931063
c  1    0.435406
   2    2.030317
dtype: float64

In [11]:
data.ix[['b','d']]

b  1   -0.432139
   2    0.043440
   3    0.931063
d  2    2.258260
   3   -1.096666
dtype: float64

In [12]:
data[:,2]

a    0.852343
b    0.043440
c    2.030317
d    2.258260
dtype: float64

In [13]:
data.unstack()

1         2         3
a -0.749082  0.852343 -0.577507
b -0.432139  0.043440  0.931063
c  0.435406  2.030317       NaN
d       NaN  2.258260 -1.096666

In [14]:
data.unstack().stack()

a  1   -0.749082
   2    0.852343
   3   -0.577507
b  1   -0.432139
   2    0.043440
   3    0.931063
c  1    0.435406
   2    2.030317
d  2    2.258260
   3   -1.096666
dtype: float64

In [15]:
frame = DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])

In [16]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [17]:
frame.index.names = ['key1','key2']

In [18]:
frame.columns.names = ['state','color']

In [19]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [20]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [21]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [24]:
frame.sortlevel(1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  """Entry point for launching an IPython kernel.


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [25]:
frame.swaplevel(0,1).sortlevel(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  """Entry point for launching an IPython kernel.


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [26]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [29]:
frame.sum(level='color',axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [30]:
frame = DataFrame({'a':range(7),'b':range(7,0,-1),'c':['one','one','one','two','two','two','two'],'d':[0,1,2,0,1,2,3]})

In [31]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [32]:
frame2 = frame.set_index(['c','d'])

In [33]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [34]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [35]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [39]:
ser = Series(np.arange(3.))

In [52]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [43]:
ser2 = Series(np.arange(3.),index=['a','b','c'])

In [44]:
ser2[-1]

2.0

In [46]:
ser.ix[:1]

0    0.0
1    1.0
dtype: float64

In [47]:
ser3 = Series(range(3),index=[-5,1,3])

In [57]:
ser3

-5    0
 1    1
 3    2
dtype: int32

In [58]:
frame = DataFrame(np.arange(6).reshape(3,2),index=[2,0,1])

In [60]:
frame

0  1
2  0  1
0  2  3
1  4  5

In [64]:
from pandas_datareader import data as web